VERSION=1.0.938.1
PACKAGE=zcs-lib-jtidy
MAINTAINER=Enrico Weigelt <enrico.weigelt@vnc.biz>
SECTION=base
ARCHITECTURE=All
PRIORITY=optional
DEPENDS=
DESCRIPTION=jTidy java library
REDMINE_UPLOAD_URL=https://redmine.vnc.biz/redmine/
REDMINE_UPLOAD_PROJECT=zcs-lib-jtidy
