TOPDIR=../..

BUILD_ANT_SUBDIR=$(TOPDIR)/jtidy
BUILD_ANT_JARFILE=$(TOPDIR)/jtidy/target/jtidy-r938.jar
BUILD_ANT_TARGET=

INSTALL_USER=y
INSTALL_ADMIN=y
INSTALL_SERVICE=y
INSTALL_LIB=y
INSTALL_ZIMLET=y

include $(TOPDIR)/common.mk
include $(ZIMBRA_BUILD_ROOT)/extensions-extra/zmpkg/mk/zcs-java-lib-ant.mk
